### ISSUE TITLE
AntStatistics dependencies are not lists

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tonyxx7/antstatistics#1]
```
What steps will reproduce the problem?
1. Try to run ant-statistics without adding any specific dependencies

What is the expected output? What do you see instead?
A graph, I think. Instead I get a stacktrace

What version of the product are you using? On what operating system?
Using ant-statistics 0.2.2 on Mac OS X 10.6 with apache-ant 1.7.1

Please provide any additional information below.

What dependencies are there? There's nothing about it on the home-page or wiki 
pages. Here is the log

$ ant -logger de.pellepelster.ant.statistics.AntStatisticsLogger -f build.xml 
full-build                                                                      

Buildfile: build.xml
The specified logger class de.pellepelster.ant.statistics.AntStatisticsLogger 
could not be used because Class 
de.pellepelster.ant.statistics.AntStatisticsLogger could not be loaded because 
of an invalid dependency.
java.lang.RuntimeException
        at org.apache.tools.ant.Main.createLogger(Main.java:850)
        at org.apache.tools.ant.Main.addBuildListeners(Main.java:795)
        at org.apache.tools.ant.Main.runBuild(Main.java:681)
        at org.apache.tools.ant.Main.startAnt(Main.java:217)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:257)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:104)
```

Original issue reported on code.google.com by `BostonVaulter` on 15 Nov 2010 at 3:10

**Comment by GoogleCodeExporter** [comment]
Original comment by `pellepel...@gmail.com` on 20 Feb 2011 at 10:11
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Hi,

id have exactly the the same issue :

java version "1.6.0_25"
Java(TM) SE Runtime Environment (build 1.6.0_25-b06)
Java HotSpot(TM) 64-Bit Server VM (build 20.0-b11, mixed mode)

and finally gest the following stacktrace :

The specified logger class de.pellepelster.ant.statistics.AntStatisticsLogger co
uld not be used because Class de.pellepelster.ant.statistics.AntStatisticsLogger
 could not be loaded because of an invalid dependency.
java.lang.RuntimeException
        at org.apache.tools.ant.Main.createLogger(Main.java:915)
        at org.apache.tools.ant.Main.addBuildListeners(Main.java:860)
        at org.apache.tools.ant.Main.runBuild(Main.java:721)
        at org.apache.tools.ant.Main.startAnt(Main.java:217)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

What do i have to do to make it run ?

Thank you in advance for any help. (the antstatistics jar has been dropped 
straight in $ANT_HOME/lib)

Best Regards,

Adrien


```

Original comment by `adrien.s...@gmail.com` on 12 May 2011 at 4:09

**Comment by GoogleCodeExporter** [comment]
```
Ok for dependencies,

just download from the web :

ant-contrib-1.0b3.jar
commons-lang-2.6.jar
jcommon-1.0.16.jar
jfreechart-1.0.13.jar
xstream-1.3.1.jar

and drop them in $ANT_HOME/lib


Stil, i'm not able to figure out how to get a nice chart

Dummy output looks like 

BUILD SUCCESSFUL
Total time: 0 seconds
+------------------------------------------------+
|                   MairieLdap                   |
+------------------------------------------------+
|       Target       | Duration (s) | Duration % |
+------------------------------------------------+
| import.mairie.ldap |      0       |  109,00%   |
|        test        |      0       |   3,00%    |
+------------------------------------------------+
|               total time (s): 0                |
+------------------------------------------------+


```

Original comment by `adrien.s...@gmail.com` on 12 May 2011 at 4:39

**Comment by GoogleCodeExporter** [comment]
```
Everyhting runs fine.

antstatistics directory is AUTOMATICALLY created durung ant run, in the working 
directory.
To customize, as mentionned, just add in the build.xml file (on the top) :

<!-- antstatistics properties -->
  <property name="antstatistics.history.expire " value="5"/>
  <property name="antstatistics.chart.height " value="800"/>
  <property name="antstatistics.chart.width " value="600"/>
  <property name="antstatistics.target.threshold" value="200"/>
  <property name="antstatistics.directory" value="toto"/>



Thanks for this very nice project.

Best Regards,

Adrien

```

Original comment by `adrien.s...@gmail.com` on 12 May 2011 at 4:47
